# Generated by Django 4.0 on 2025-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
